"""
Email Integration
=================

Send email notifications for changes and approvals.
"""

from __future__ import annotations

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from html import escape
from typing import Any, Dict, List, Optional

from loguru import logger


class EmailNotifier:
    """Email notification service."""
    
    def __init__(
        self,
        smtp_host: str = "localhost",
        smtp_port: int = 587,
        username: Optional[str] = None,
        password: Optional[str] = None,
        from_address: str = "fabric-agent@company.com",
        use_tls: bool = True,
    ):
        self.smtp_host = smtp_host
        self.smtp_port = smtp_port
        self.username = username
        self.password = password
        self.from_address = from_address
        self.use_tls = use_tls
    
    def notify_impact(
        self,
        recipients: List[str],
        impact_report: Any,
    ) -> bool:
        """Send impact report via email."""
        source_name = impact_report.source_asset.name if impact_report.source_asset else "Unknown"
        subject = f"[Fabric Agent] Impact Analysis: {source_name}"
        body = self._build_impact_html(impact_report)
        return self._send_email(recipients, subject, body)
    
    def request_approval(
        self,
        recipients: List[str],
        plan: Any,
        approval_url: Optional[str] = None,
    ) -> bool:
        """Send approval request via email."""
        subject = f"[Fabric Agent] Approval Required: {plan.source_change}"
        body = self._build_approval_html(plan, approval_url)
        return self._send_email(recipients, subject, body)

    def notify_schema_drift_impact(
        self,
        recipients: List[str],
        payload: Dict[str, Any],
    ) -> bool:
        """Send schema-drift alert with downstream impact and required changes."""
        source = payload.get("source", {})
        workspace = source.get("workspace", "unknown-workspace")
        lakehouse = source.get("lakehouse", "unknown-lakehouse")
        table = source.get("table", "unknown-table")
        subject = (
            "[Fabric Agent] Schema Drift Alert: "
            f"{workspace}/{lakehouse}.{table}"
        )
        body = self._build_schema_drift_impact_html(payload)
        return self._send_email(recipients, subject, body)
    
    def _build_impact_html(self, report: Any) -> str:
        """Build HTML email for impact report."""
        source_name = report.source_asset.name if report.source_asset else "Unknown"
        
        warnings_html = ""
        if report.warnings:
            warnings_html = "<h3>⚠️ Warnings</h3><ul>"
            for w in report.warnings:
                warnings_html += f"<li>{w}</li>"
            warnings_html += "</ul>"
        
        return f"""
        <html>
        <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h2>🔍 Impact Analysis Report</h2>
            
            <table style="width: 100%; border-collapse: collapse;">
                <tr>
                    <td style="padding: 8px; border: 1px solid #ddd;"><strong>Source</strong></td>
                    <td style="padding: 8px; border: 1px solid #ddd;">{source_name}</td>
                </tr>
                <tr>
                    <td style="padding: 8px; border: 1px solid #ddd;"><strong>Change</strong></td>
                    <td style="padding: 8px; border: 1px solid #ddd;">{report.change_type}</td>
                </tr>
                <tr>
                    <td style="padding: 8px; border: 1px solid #ddd;"><strong>Risk Level</strong></td>
                    <td style="padding: 8px; border: 1px solid #ddd;">{report.risk_level.value.upper()} ({report.risk_score}/100)</td>
                </tr>
                <tr>
                    <td style="padding: 8px; border: 1px solid #ddd;"><strong>Total Affected</strong></td>
                    <td style="padding: 8px; border: 1px solid #ddd;">{report.total_affected}</td>
                </tr>
            </table>
            
            <h3>📊 Affected Assets</h3>
            <ul>
                <li>Measures: {len(report.affected_measures)}</li>
                <li>Reports: {len(report.affected_reports)}</li>
                <li>Notebooks: {len(report.affected_notebooks)}</li>
                <li>Pipelines: {len(report.affected_pipelines)}</li>
            </ul>
            
            {warnings_html}
            
            <p style="color: #666; font-size: 12px;">
                Generated by Fabric Agent
            </p>
        </body>
        </html>
        """
    
    def _build_approval_html(self, plan: Any, approval_url: Optional[str]) -> str:
        """Build HTML email for approval request."""
        approve_link = f'<a href="{approval_url}?action=approve">✅ Approve</a>' if approval_url else ""
        
        return f"""
        <html>
        <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h2>🔐 Approval Required</h2>
            
            <p><strong>Change:</strong> {plan.source_change}</p>
            <p><strong>From:</strong> <code>{plan.old_value}</code> → <code>{plan.new_value}</code></p>
            
            <table style="width: 100%; border-collapse: collapse;">
                <tr>
                    <td style="padding: 8px; border: 1px solid #ddd;"><strong>Total Actions</strong></td>
                    <td style="padding: 8px; border: 1px solid #ddd;">{len(plan.actions)}</td>
                </tr>
                <tr>
                    <td style="padding: 8px; border: 1px solid #ddd;"><strong>Auto-Fixable</strong></td>
                    <td style="padding: 8px; border: 1px solid #ddd;">{plan.auto_fix_count}</td>
                </tr>
                <tr>
                    <td style="padding: 8px; border: 1px solid #ddd;"><strong>Manual Required</strong></td>
                    <td style="padding: 8px; border: 1px solid #ddd;">{plan.manual_count}</td>
                </tr>
            </table>
            
            <p style="margin-top: 20px;">
                {approve_link}
            </p>
            
            <p style="color: #666; font-size: 12px;">
                Please review and approve this change request.
            </p>
        </body>
        </html>
        """
    
    def _build_schema_drift_impact_html(self, payload: Dict[str, Any]) -> str:
        """Build HTML email for schema drift + downstream impact."""
        source = payload.get("source", {})
        drift = payload.get("drift", {})
        impact = payload.get("impact", {})
        summary = impact.get("summary", {})
        required_changes = payload.get("required_changes", []) or []

        def _li(values: List[str]) -> str:
            if not values:
                return "<li>none</li>"
            return "".join(f"<li>{escape(v)}</li>" for v in values)

        source_ref = (
            f"{source.get('workspace', 'unknown')}/"
            f"{source.get('lakehouse', 'unknown')}."
            f"{source.get('table', 'unknown')}"
        )

        added = drift.get("added", []) or []
        removed = drift.get("removed", []) or []
        type_changed = drift.get("type_changed", []) or []
        nullability_changed = drift.get("nullability_changed", []) or []

        changed_type_lines = [
            f"{c.get('name')}: {c.get('from')} -> {c.get('to')}"
            for c in type_changed
        ]
        nullability_lines = [
            f"{c.get('name')}: {c.get('from')} -> {c.get('to')}"
            for c in nullability_changed
        ]

        return f"""
        <html>
        <body style="font-family: Arial, sans-serif; max-width: 760px; margin: 0 auto;">
            <h2>Schema Drift Alert</h2>
            <p><strong>Source Table:</strong> <code>{escape(source_ref)}</code></p>
            <table style="width: 100%; border-collapse: collapse;">
                <tr><td style="padding:8px; border:1px solid #ddd;"><strong>Breaking Change</strong></td><td style="padding:8px; border:1px solid #ddd;">{escape(str(drift.get("breaking", False)))}</td></tr>
                <tr><td style="padding:8px; border:1px solid #ddd;"><strong>Risk Level</strong></td><td style="padding:8px; border:1px solid #ddd;">{escape(str(summary.get("risk_level", "unknown")))}</td></tr>
                <tr><td style="padding:8px; border:1px solid #ddd;"><strong>Total Downstream Impact</strong></td><td style="padding:8px; border:1px solid #ddd;">{escape(str(summary.get("total_downstream_assets", 0)))}</td></tr>
                <tr><td style="padding:8px; border:1px solid #ddd;"><strong>Consumer Workspaces Impacted</strong></td><td style="padding:8px; border:1px solid #ddd;">{escape(str(summary.get("consumer_workspaces_impacted", 0)))}</td></tr>
            </table>

            <h3>Detected Drift</h3>
            <ul>
                <li>Added columns: {len(added)}</li>
                <li>Removed columns: {len(removed)}</li>
                <li>Type changes: {len(type_changed)}</li>
                <li>Nullability changes: {len(nullability_changed)}</li>
            </ul>

            <h4>Type Changes</h4>
            <ul>{_li(changed_type_lines)}</ul>

            <h4>Nullability Changes</h4>
            <ul>{_li(nullability_lines)}</ul>

            <h3>Required Changes</h3>
            <ul>{_li(required_changes)}</ul>

            <p style="color: #666; font-size: 12px;">
                Generated by Fabric Agent. Review before promoting pipeline updates.
            </p>
        </body>
        </html>
        """

    def _send_email(
        self,
        recipients: List[str],
        subject: str,
        body: str,
    ) -> bool:
        """Send email via SMTP."""
        try:
            msg = MIMEMultipart("alternative")
            msg["Subject"] = subject
            msg["From"] = self.from_address
            msg["To"] = ", ".join(recipients)
            
            msg.attach(MIMEText(body, "html"))
            
            with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
                if self.use_tls:
                    server.starttls()
                if self.username and self.password:
                    server.login(self.username, self.password)
                server.sendmail(self.from_address, recipients, msg.as_string())
            
            logger.info(f"Email sent to {len(recipients)} recipients")
            return True
        except Exception as e:
            logger.error(f"Email failed: {e}")
            return False
